name: Hugo Actions

on:
  push:
    branches:
      - main  # 当你修改并提交代码到 main 分支时触发

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # 获取主题文件
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.122.0'
          extended: true # 建议开启扩展版，兼容性更好

      - name: Build Site
        run: |
          # 这一步是把你 exampleSite 里的装修材料搬到大门口
          cp -R exampleSite/* .
          # 注意：下面的 URL 已经改成了你的 GitHub 账号名
          hugo --themesDir ../ --baseURL https://shangguan6636.github.io/WebStack-Hugo/
          
      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # 使用 GitHub 自带的令牌，不需要你额外去生成所谓的 Personal Access Token
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public    
          publish_branch: gh-pages # 将生成的网页放在 gh-pages 分支
          force_orphan: true
